<a href="https://colab.research.google.com/github/JFrankVC/deepL-intro/blob/main/ch03_introTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**3.5 First steps with TensorFlow**

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.ones(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [ ]:
x = tf.zeros(shape=(2, 1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [ ]:
x = tf.random.normal(shape=(3, 1), mean=0., stddev=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-2.009307  ],
       [-2.037219  ],
       [ 0.24709134]], dtype=float32)>

In [5]:
x = tf.random.uniform(shape=(3, 1), minval=0., maxval=1.)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.73624134],
       [0.8417617 ],
       [0.48893988]], dtype=float32)>

In [7]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0, 0] = 0.
x

array([[0., 1.],
       [1., 1.]])

In [9]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[0.219363  ],
       [0.42281136],
       [0.83928514]], dtype=float32)>

In [10]:
v.assign(tf.ones((3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [11]:
v[0, 0].assign(3.)
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [12]:
v.assign_add(tf.ones((3, 1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [15]:
a = tf.ones((2, 2))*2
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [16]:
c = tf.sqrt(a)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

In [17]:
d = b + c
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5.4142137, 5.4142137],
       [5.4142137, 5.4142137]], dtype=float32)>

In [18]:
e = tf.matmul(a, b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[16., 16.],
       [16., 16.]], dtype=float32)>

In [19]:
e *= d
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[86.62742, 86.62742],
       [86.62742, 86.62742]], dtype=float32)>

***3.5.3 GradientTape API***

${\displaystyle \nabla f(p)={\begin{bmatrix}{\frac {\partial f}{\partial x_{1}}}(p)\\\vdots \\{\frac {\partial f}{\partial x_{n}}}(p)\end{bmatrix}}}$

In [26]:
input_var = tf.Variable(initial_value=3.)
print(f"input var = {input_var}")
with tf.GradientTape() as tape:
   result = tf.square(input_var)
   print(f"result = {result}")
gradient = tape.gradient(result, input_var)
print(f"gradient = {gradient}")

input var = <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
result = 9.0
gradient = 6.0


In [29]:
input_const = tf.constant(3.)
print(f"input const = {input_const}")
with tf.GradientTape() as tape:
   tape.watch(input_const)
   result = tf.square(input_const)
   print(f"result = {result}")
gradient = tape.gradient(result, input_const)
print(f"gradient = {gradient}")

input const = 3.0
result = 9.0
gradient = 6.0


In [32]:
# Second order gradient (e.g., accel)
time = tf.Variable(3.)
print(f"time = {time}")
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as inner_tape:
        position =  4.9 * time ** 2
        print(f"pos = {position}")
    speed = inner_tape.gradient(position, time)
    print(f"speed = {speed}")
acceleration = outer_tape.gradient(speed, time)
print(f"accel = {acceleration}")

time = <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
pos = 44.10000228881836
speed = 29.400001525878906
accel = 9.800000190734863
